# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f4ce5be7d099d7c92e658e23f8e0538f2f4f66e6f0471b485cb4fcaa43e98c6a51fc88c38da200b2bec47f6d47d6a21c0a0a848ed9c1794e13838c1220341d2

test:
  secret_key_base: 0157c3936db8fdcd18aa1b27dddfd23ce3505d29f9e333d7d20499ec35bc1d049da342a13ede6960d8b8cdf4ae34387f92b4a113dff32e4563052c59c43ef07b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
